default:
	adapter: postgres
	host: localhost
  username: dev_username
  password: dev_password

development:
  database: lobsters_dev
  
test:
  database: lobsters_test

production:
	database: lobsters_production
