default: &default
  adapter: postgresql
  host: localhost
  # username: dev_username
  # password: dev_password

development:
  <<: *default
  database: lobsters_dev

test:
  <<: *default
  database: lobsters_test

production:
  <<: *default
  database: lobsters_production
